// Constants for JobJourney Extension - Side Panel
import type { CountryConfig, Platform, PlatformId } from '@extension/types';

export const PLATFORMS: Partial<Record<PlatformId, Platform>> = {
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: '💼',
    domains: ['linkedin.com'],
    color: '#0077b5',
    enabled: true,
  },
  seek: {
    id: 'seek',
    name: 'SEEK',
    icon: '🔍',
    domains: ['seek.com.au', 'seek.co.nz'],
    color: '#0d3880',
    enabled: true,
  },
  // Indeed temporarily disabled
  // indeed: {
  //   id: 'indeed',
  //   name: 'Indeed',
  //   icon: '📋',
  //   domains: ['indeed.com'],
  //   color: '#2164f3',
  //   enabled: false,
  // },
  jora: {
    id: 'jora',
    name: 'Jora',
    icon: '🧭',
    domains: ['jora.com'],
    color: '#00a1e0',
    enabled: true,
  },
  reed: {
    id: 'reed',
    name: 'Reed',
    icon: '🇬🇧',
    domains: ['reed.co.uk'],
    color: '#d4002a',
    enabled: true,
  },
};

export const COUNTRIES: Record<string, CountryConfig> = {
  US: {
    name: 'United States',
    code: 'US',
    icon: '🇺🇸',
    platforms: ['linkedin' as PlatformId],
    locations: [
      'New York, NY',
      'Los Angeles, CA',
      'Chicago, IL',
      'Houston, TX',
      'Phoenix, AZ',
      'Philadelphia, PA',
      'San Antonio, TX',
      'San Diego, CA',
      'Dallas, TX',
      'San Jose, CA',
      'Austin, TX',
      'Jacksonville, FL',
      'Fort Worth, TX',
      'Columbus, OH',
      'Charlotte, NC',
      'San Francisco, CA',
      'Indianapolis, IN',
      'Seattle, WA',
      'Denver, CO',
      'Washington, DC',
      'Boston, MA',
      'El Paso, TX',
      'Nashville, TN',
      'Detroit, MI',
      'Oklahoma City, OK',
      'Portland, OR',
      'Las Vegas, NV',
      'Memphis, TN',
      'Louisville, KY',
      'Baltimore, MD',
      'Milwaukee, WI',
      'Albuquerque, NM',
      'Tucson, AZ',
      'Fresno, CA',
      'Mesa, AZ',
      'Sacramento, CA',
      'Atlanta, GA',
      'Kansas City, MO',
      'Colorado Springs, CO',
      'Miami, FL',
      'Raleigh, NC',
      'Omaha, NE',
      'Long Beach, CA',
      'Virginia Beach, VA',
      'Oakland, CA',
      'Minneapolis, MN',
      'Tampa, FL',
      'Tulsa, OK',
      'Arlington, TX',
      'New Orleans, LA',
    ],
    urls: {},
  },
  AU: {
    name: 'Australia',
    code: 'AU',
    icon: '🇦🇺',
    platforms: ['linkedin' as PlatformId, 'seek' as PlatformId, 'jora' as PlatformId],
    locations: [
      'Sydney, NSW',
      'Melbourne, VIC',
      'Brisbane, QLD',
      'Perth, WA',
      'Adelaide, SA',
      'Gold Coast, QLD',
      'Newcastle, NSW',
      'Canberra, ACT',
      'Hobart, TAS',
      'Darwin, NT',
      'Townsville, QLD',
      'Cairns, QLD',
      'Toowoomba, QLD',
      'Ballarat, VIC',
      'Bendigo, VIC',
      'Albury, NSW',
      'Launceston, TAS',
      'Mackay, QLD',
      'Rockhampton, QLD',
      'Bunbury, WA',
      'Bundaberg, QLD',
      'Coffs Harbour, NSW',
      'Wagga Wagga, NSW',
      'Hervey Bay, QLD',
      'Mildura, VIC',
      'Shepparton, VIC',
      'Port Macquarie, NSW',
      'Gladstone, QLD',
      'Tamworth, NSW',
      'Traralgon, VIC',
      'Orange, NSW',
      'Dubbo, NSW',
      'Geraldton, WA',
      'Nowra, NSW',
      'Warrnambool, VIC',
      'Kalgoorlie, WA',
      'Albany, WA',
      'Blue Mountains, NSW',
      'Lismore, NSW',
      'Goulburn, NSW',
    ],
    urls: {},
  },
  UK: {
    name: 'United Kingdom',
    code: 'UK',
    icon: '🇬🇧',
    platforms: ['linkedin' as PlatformId, 'reed' as PlatformId],
    locations: [
      'London',
      'Manchester',
      'Birmingham',
      'Leeds',
      'Glasgow',
      'Liverpool',
      'Edinburgh',
      'Bristol',
      'Sheffield',
      'Newcastle',
      'Nottingham',
      'Cardiff',
      'Belfast',
      'Leicester',
      'Coventry',
      'Bradford',
      'Stoke-on-Trent',
      'Wolverhampton',
      'Plymouth',
      'Derby',
      'Southampton',
      'Swansea',
      'Reading',
      'Northampton',
      'Luton',
      'Milton Keynes',
      'Warrington',
      'York',
      'Poole',
      'Bournemouth',
      'Peterborough',
      'Cambridge',
      'Oxford',
      'Blackpool',
      'Ipswich',
      'Norwich',
      'Exeter',
      'Chelmsford',
      'Gloucester',
      'Aberdeen',
      'Dundee',
      'Stirling',
      'Inverness',
    ],
    urls: {},
  },
  CA: {
    name: 'Canada',
    code: 'CA',
    icon: '🇨🇦',
    platforms: ['linkedin' as PlatformId],
    locations: [
      'Toronto, ON',
      'Vancouver, BC',
      'Montreal, QC',
      'Calgary, AB',
      'Ottawa, ON',
      'Edmonton, AB',
      'Winnipeg, MB',
      'Quebec City, QC',
      'Hamilton, ON',
      'Kitchener, ON',
      'London, ON',
      'Halifax, NS',
      'Victoria, BC',
      'Windsor, ON',
      'Oshawa, ON',
      'Saskatoon, SK',
      'Regina, SK',
      'Sherbrooke, QC',
      "St. John's, NL",
      'Barrie, ON',
      'Kelowna, BC',
      'Abbotsford, BC',
      'Kingston, ON',
      'Sudbury, ON',
      'Chicoutimi, QC',
      'Thunder Bay, ON',
      'Saint John, NB',
      'Moncton, NB',
      'Kamloops, BC',
      'Brantford, ON',
      'Cape Breton, NS',
      'Chatham-Kent, ON',
      'Red Deer, AB',
      'Lethbridge, AB',
      'Nanaimo, BC',
      'Fredericton, NB',
      'Medicine Hat, AB',
      'Sarnia, ON',
      'Grande Prairie, AB',
      'Charlottetown, PE',
    ],
    urls: {},
  },
  NZ: {
    name: 'New Zealand',
    code: 'NZ',
    icon: '🇳🇿',
    platforms: ['linkedin' as PlatformId, 'seek' as PlatformId],
    locations: [
      'Auckland',
      'Wellington',
      'Christchurch',
      'Hamilton',
      'Tauranga',
      'Dunedin',
      'Palmerston North',
      'Napier-Hastings',
      'Nelson',
      'Rotorua',
      'New Plymouth',
      'Whangarei',
      'Invercargill',
      'Whanganui',
      'Gisborne',
      'Blenheim',
      'Masterton',
      'Timaru',
      'Oamaru',
      'Greymouth',
      'Westport',
      'Hokitika',
      'Te Awamutu',
      'Pukekohe',
      'Tokoroa',
      'Levin',
      'Ashburton',
      'Gore',
      'Whakatane',
      'Rangiora',
    ],
    urls: {},
  },
};
